[package]
name = "pcg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
derive-getters = "0.2.0"
priority-queue = "1.2.3"
xmlwriter = "0.1.0"
regex = "1.6.0"
relative-path = "1.7.2"